version: '3'
services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.0.1
    container_name: control-center
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
    depends_on:
      - kafka
    networks:
      - kafka-net

volumes:
  zookeeper-data:
  kafka-data:

networks:
  kafka-net:
    driver: bridge